### ISSUE TITLE
퍼즐 마무리 & 불 만들기

### ISSUE THREAD

**Issue by 20silver** [nelumbotus/Team_GPL#11]
1. 퍼즐이 에셋에서 제대로 작동이 안돼서 작동 되도록 하기
2. 퍼즐 디자인 더 멋있게 만들어보기
3. 초에 없는 불 만들기

**Comment by okdalto** [comment]
양초에 불 만들때 광원이랑 쉐이더 추가해야 할 것 같습니다.
