### ISSUE TITLE
[퍼즐] 별자리 트릭 완성하기

### ISSUE THREAD

**Issue by yeonkyeong-lee** [nelumbotus/Team_GPL#5]
- 손전등 에셋찾기 , 별자리 그래픽과 별자리 해설 표 그래픽 완성하고 트릭에 적용하기

**Comment by asteroid-612** [comment]
손전등을 위해서 
- 마우스 분해후 배터리 찾기 ( 도전과제 )
- 손전등을 찾는 방법에 퍼즐이 필요.
