### ISSUE TITLE
게임매니저 만들기

### ISSUE THREAD

**Issue by yeonkyeong-lee** [nelumbotus/Team_GPL#6]
전반적인 게임 관리를 할 게임매니저 만들기

**각자 게임매니저가 필요한 부분을 댓글로 달아주시면 게임매니저 오브젝트에 적용하도록 하겠습니다 ~~ **

**Comment by okdalto** [comment]
게임매니저에 enum으로 현재 게임 상태를 만들어야 할 것 같아요. 

예를 들어 플레이어 조작하는 코드가 게임메니저 안의 게임상태 참조해서 물건을 들어서 보고 있을때는 작동하지 않도록, 그렇게 만들어야 할 것 같습니다.

**Comment by okdalto** [comment]
UI도 게임매니저에서 만들고 관리하는 게 좋을 것 같습니다.
